version: '3.11'

services:
  web:
    container_name: web
    hostname: web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "9000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - chrome

  db:
    image: postgres:15
    container_name: db
    hostname: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: adick
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: adick
    ports:
      - "6543:5432"
  redis:
    image: redis:7.0

  chrome:
    image: selenium/node-chrome:dev
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"